### ISSUE TITLE
Limited Oregen

### ISSUE THREAD

**Issue by q256us** [TelepathicGrunt/UltraAmplifiedMod#11]
Most mods ores only generate in spawn chunks of 1.15.2 UA overworld dimension, when using UA overworld worldgen.  UA is only generating Vanilla, UA, plus ONE other mod's ores (Silent Gems) even as a separate dimension.  Mod pack with Silent Gems, Silent Mechanism, Omega, Powah, and Large Ore Deposits, only generates Silent Gems outside small area around spawn. Other Dimension (Dream/Nightmare) and world gen types (Island Generator) have no issues generating these ores.

**Comment by TelepathicGrunt** [comment]
The reason many oregen mods won't place ores with Ultra Amplified is because the biomes in the dimension are not vanilla biomes at all. they are custom Ultra Amplifies version of vanilla biomes. If you want to import modded ores into Ultra Amplified, try turning on the importModdedFeatures config option in UA's config file (can be found in the serverconfig folder inside the world's own save folder). 

Let me know if this works and especially let me know if importModdedFeatures doesn't work so I can see why the config is not adding the modded ores from vanilla biomes. 

But hopefully it will work. :)

**Comment by q256us** [comment]
Thank You for the quick response.  Indeed, that option does resolve the issue. I guess the other mods and spawn chunks must be ignoring the biome when generating ores.

**Comment by TelepathicGrunt** [comment]
It's actually due to how ultra amplified works with its per world config. Every time you enter the dimension, it resets all the features in the UA biomes and then uses the config to know if it should add back in modded stuff from the corresponding vanilla biomes. Sadly, there is that one bug where the spawn chunk is always made before the config is read and there is no forge event that fires earlier per world rip. 

But glad it works now for you! :)
