### ISSUE TITLE
World Crashed While Generating Chunk

### ISSUE THREAD

**Issue by ClaudiusMinimus** [TelepathicGrunt/UltraAmplifiedMod#18]
A test player was flying, but not too fast according to him. The chunks were generating and then the server crashed. After restarting the server, the chunk loaded fine. Here is the crash report.

- Minecraft Version: 1.15.2
- Operating System: Linux (amd64) version 4.15.0-99-generic
- Java Version: 1.8.0_251, Oracle Corporation
- Forge: 31.2.0
- ultra_amplified_dimension-1.15.2-8.0.2

[crash-2020-06-02_23.54.44-server.txt](https://github.com/TelepathicGrunt/UltraAmplifiedMod/files/4719908/crash-2020-06-02_23.54.44-server.txt)

**Comment by TelepathicGrunt** [comment]
Looks like a bad mixin was done by someone that modified an arraylist during worldgen.
From what I can tell, line 11 seems to point to `ruins-1.15.1.3.jar Ruins` as the cause which is strange. 
Is Ruins this mod?
https://www.curseforge.com/minecraft/mc-mods/ruins-structure-spawning-system

Try removing the mod and see if that solves the crash. If there's too many mods on that relies on Ruins, it might be good to open an issue report with them to let them know they should make sure they setup their mixin properly

**Comment by TelepathicGrunt** [comment]
Oh no, it's not a mixin... It's a Javascript coremod! Oh god. Why is Forge reporting JS Coremods as mixins? That's terrifying lol.

But yeah, I ain't touching JS coremods with a 10 foot pole at all. Let the other mod know they messed up their JS coremod and to make it so it doesn't break worldgen

**Comment by TelepathicGrunt** [comment]
Actually wait, I was wrong.
`re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:extratags.mixins.json:BiomeMixin,pl:mixin:A,pl:runtimedistcleaner:A`

This line means the class was touched by a ton of coremods including accesstransformers, mixins,  etc. Since so many mods has modified that Biome class, there's really no way to tell which mod is the issue now. Sorry.

You may have to do trial and error to see which mod's modification is breaking worldgen. I wish I could help more but I got nothing. Though check if Ruins or extratags could be the issue as those two are listed but it could be a completely different mod too.

**Comment by ClaudiusMinimus** [comment]
Thank you for your help! I will do as you say.

**Comment by ClaudiusMinimus** [comment]
I have removed Ruins and so far everything seems okay. I look forward to Suzy adding new structures instead of using Ruins.
