### ISSUE TITLE
Biome Blacklist Failing

### ISSUE THREAD

**Issue by ClaudiusMinimus** [TelepathicGrunt/UltraAmplifiedMod#19]
Today for some reason the biome blacklist seems to be failing. I updated forge yesterday and noticed this change today.

**Snippet from**: _/world/serverconfig/ultra_amplified_dimension-server.toml_
`blacklistedBiomeList = "endergetic:*, midnight:*, rats:*, mining_dimension:*"`

![2020-06-17_12 09 19](https://user-images.githubusercontent.com/17887664/84934515-a8b05c00-b094-11ea-81b3-a08a90f5e1ae.png)

- Minecraft Version: 1.15.2
- Operating System: Linux (amd64) version 4.15.0-99-generic
- Java Version: 1.8.0_251, Oracle Corporation
- Forge: 31.2.20
- ultra_amplified_dimension-1.15.2-8.0.3

[debug.log](https://github.com/TelepathicGrunt/UltraAmplifiedMod/files/4794432/debug.log)
[latest.log](https://github.com/TelepathicGrunt/UltraAmplifiedMod/files/4794434/latest.log)

**Comment by TelepathicGrunt** [comment]
Ah shoot i kept forgetting to get back to investigate this issue. Is it still an issue? if so, try moving the config file out of the config folder, run the game so it makes a new one, and then try the config entry again. I say this because i noticed this line in the logs:
`[17Jun2020 20:11:32.983] [Server thread/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Configuration file ./world/serverconfig/ultra_amplified_dimension-server.toml is not correct. Correcting`

So the config file might be messed up which could cause it to not read the config correctly.

**Comment by TelepathicGrunt** [comment]
Just tested with forge 31.2.21 using rats, endergetic, and midnight. From what I can tell, the config worked for me so I'm guessing for some weird reason, the config file your server was using was malformed in some way. Make a copy of it and put the copy elsewhere so you dont lose what your entries were and then delete the original from the game. Then have the game regenerate the config. then put your entries back in and it should work again. Let me know if it still doesnt!

**Comment by TelepathicGrunt** [comment]
Closing as 1.16.4 release is soon and 1.15.4 support is now being dropped as a result.
