### ISSUE TITLE
Portal conflicts with Create

### ISSUE THREAD

**Issue by StormCircuit** [TelepathicGrunt/UltraAmplifiedMod#25]
Create renamed polished Granite and polished Diorite to Layered Granite and Layered Diorite. The corner blocks can be replaced with a datapack but the center diorite block can not meaning with both mods one can't access the dimension without re-enabling the polished blocks via create.

**Comment by TelepathicGrunt** [comment]
Uhh are you sure it is Create? I am able to make polished diorite and others with Create on and the portal still works.
![image](https://user-images.githubusercontent.com/40846040/107877310-93950280-6e99-11eb-9df4-f4b9c72c4dc2.png)

![image](https://user-images.githubusercontent.com/40846040/107877318-a3ace200-6e99-11eb-8b2d-38d1468b7631.png)

I just didn't have a tag for the diorite of portals because the portal block itself is textured after polished diorite and drops polished diorite when mined. It would be a lot of work to make it dynamic and stuff.

**Comment by TelepathicGrunt** [comment]
ah I see Create adds the layer variants of these blocks. But they do not remove the original blocks and the original blocks are still craftable. So there should be no issue here lol. I'll close this report now

**Comment by StormCircuit** [comment]
That's odd I can't seen to craft them. I must be having an issue with another mod. Something is removing the polished variant. Still is it possible to change the center block of the portal? Maybe I missed it?

**Comment by TelepathicGrunt** [comment]
If you can find which mod removed the polished variants, let me know as they really shouldn't do that or else they break a lot of mod's recipes.

And again on the idea of tag based center block, I just didn't have a tag for the portal's diorite because the portal block itself is textured after polished diorite and drops polished diorite when mined. It would be a lot of work to make it dynamically textured and drop the previous block it was. After all, it would be super weird if someone makes diamond block a portal block but get polished diorite when mining the portal block.

**Comment by StormCircuit** [comment]
So I did some investigating, I removed every single mod from my forge installation, all of the polished blocks - except for those added by mods - are gone. I am using forge-1.16.5-36.0.21 (0.22 causes crashes with Charm). Seeing as how the loader is in beta this very well could be a bug with Forge. I do not know how to investigate further however.

**Comment by StormCircuit** [comment]
So after reinstalling forge and minecraft the issue seems to have resolved its self. Bizarre. Sorry for updating you with a false lead!

**Comment by TelepathicGrunt** [comment]
that's wacky lol. still, glad it's now working for you!
