### ISSUE TITLE
Some chunks aren't cleared correctly

### ISSUE THREAD

**Issue by Insane96** [TelepathicGrunt/UltraAmplifiedMod#3]
![2019-11-08_13 00 45](https://user-images.githubusercontent.com/7185104/68475760-4dc6a480-0229-11ea-90e4-412d7b8dec86.png)

**Comment by TelepathicGrunt** [comment]
This bug has been around for a while due to the cave generation using a heavily modified version of the Vanilla Ravine code. I'll try and take another stab at trying to figure out what is causing this bug.

**Comment by Insane96** [comment]
Yeah iirc this happens with vanilla ravines too

Il Ven 8 Nov 2019, 14:16 TelepathicGrunt <notifications@github.com> ha
scritto:

**Comment by TelepathicGrunt** [comment]
This bug has been resolved in V.6.11.1 which is now released! :)

The issue was due to how the ravine code carves out the ledges on the walls. To fix this, Cave Cavities now generate more as a giant cylinder rather than trying to make walls that vary in directions which causes the legacy ravine code to freak out.
