### ISSUE TITLE
Server Startup Crash

### ISSUE THREAD

**Issue by supersaiyansubtlety** [TelepathicGrunt/UltraAmplifiedMod#5]
I just downloaded 4.6.1 and it worked well in single player. Then I tried to put it on my server and got this crash (I tried starting it up again to see if it was consistent, it was)

[UltrAmplified-server-startup-crash.txt](https://pastebin.com/i6W0nLvw)

It's a nosuchmethod error, so am I using the wrong version of something or is there a dependency?

**Comment by TelepathicGrunt** [comment]
Looks like a siding issues (client/world stuff) in my code. Should be an easy fix so I'll let you know when the patch comes out.

**Comment by supersaiyansubtlety** [comment]
Ok, thanks

**Comment by TelepathicGrunt** [comment]
It should be fixed in 4.6.2 now which is visible on curseforge.

Thank you again for reporting these bugs lol. Hopefully the mod is now stable for good! 

(P.S. to make the portal in v4.6.2, use Stone Brick Slabs as I forgot players cannot get Smooth Stone in 1.12 survival. I've been playing 1.14 too much...)

**Comment by supersaiyansubtlety** [comment]
Everything seems to be working now, thanks!
