### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by NielsPilgaard** [TelepathicGrunt/UltraAmplifiedMod#7]
Hello!

One of my players started to crash on world load, after the mod FastWorkbench had been added. The stacktrace seems to point primarily at UA though, so I thought I'd start here :)

### Version
- ultra_amplified_dimension-1.15.2-7.2.3

### Crash report
https://gist.github.com/janagyjr/094f1c8b2da9b6efde8f163bcacdb6f4

Original report: https://github.com/NillerMedDild/Enigmatica5/issues/82

**Comment by TelepathicGrunt** [comment]
Thank you for the report! I'll check it out but where the error is occurring is extremely strange. I can test this later but I suspect it's not due to Fastworkbench. 

When I try a patch, I might ask you to try it and see if the player can enter to make sure it addressed the problem before release. Would that be alright? :)

**Comment by NielsPilgaard** [comment]
Sure :)

**Comment by TelepathicGrunt** [comment]
Here's the build you can have the guy try and see if he can log into the world. It's not an issue with FastWorkBench but an issue with some data that I set on the player to make teleportation work with the Amplified Portal Block. 

if it still crashes, let me know with the new stacktrace and I should be able to pin down the issue much easier!

[ultra_amplified_dimension-1.15.2-7.2.4b.zip](https://github.com/TelepathicGrunt/UltraAmplifiedMod/files/4309560/ultra_amplified_dimension-1.15.2-7.2.4b.zip)

**Comment by NielsPilgaard** [comment]
Awesome, I'll test it this evening, thanks!

**Comment by NielsPilgaard** [comment]
I'm waiting to receive a copy of the erroring world, I'll let you know when I have some answers :)

**Comment by NielsPilgaard** [comment]
I'm afraid the issue was not fixed, here's the new crash report, though it's pretty much identical: https://gist.github.com/NillerMedDild/3c33b87e4f4096edcab6b4c30c864d26

If you feel like testing the erroring world: https://drive.google.com/file/d/1eF11LiBT-fX10NKp-CceL48mSDagqsB_/view?usp=sharing

The modpack is Enigmatica 5 version 0.3.7, just make sure to update UAD ofc :)

**Comment by TelepathicGrunt** [comment]
It appears he is not using the new jar or the server is not using the new jar or both. Looking at the Mod list in that crash report shows the line of 
"ultra_amplified_dimension-1.15.2-7.2.3.jar Ultra Amplified Dimension {ultra_amplified_dimension@1.15.2-7.2.3 DONE}"

I think it's just a simple mistake but if you can get him and make sure the server both uses the new jar, then we can know for sure if the patch worked! (it would say 7.2.4b instead of 7.2.3)

**Comment by NielsPilgaard** [comment]
I totally forgot to actually apply the new version you made, silly mistake, sorry about that :P

**Comment by NielsPilgaard** [comment]
All clear on 7.2.4, the world loads and seems functional, nice work \o/
