### ISSUE TITLE
Another Crash on world load

### ISSUE THREAD

**Issue by NielsPilgaard** [TelepathicGrunt/UltraAmplifiedMod#9]
Another crash on world load, it was resolved by loading once more though - Thought I'd link it anyway :)

### Version
- ultra_amplified_dimension-1.15.2-7.2.4

### Logs
https://pastebin.com/3g0bsc7H

Original issue: https://github.com/NillerMedDild/Enigmatica5/issues/100

**Comment by TelepathicGrunt** [comment]
odd. Let me know if the crash happens again and I'll try and spend time redoing the codebase where it is crashing. It is very old code but I don't see exactly why it would be crashing intermittently which is strange

**Comment by TelepathicGrunt** [comment]
hmm. it seems this went over a month and no other reports of this crash came up. I'll close this issue report now as it seemed to be a one time odd crash but I'll still redo the codebase later since that section of code is messy.

If you get the crash again, just let me know and re-open this issue report :)

**Comment by NielsPilgaard** [comment]
Sounds good, I haven't encountered it since either :)
